doc/Doxyfile.in
Remove explicit link to insecure link for mathjax (`http`).
Closes #37
=> [doc] Remove explicit link to mathjax

Ponca/Fitting, Ponca/src/Fitting/dryFit.h
Useful to monitor spatial partitioning performances (see https://github.com/poncateam/poncascope/pull/3)
=> [Fitting] Add dryfit: an empty fitting object

.gitignore, CHANGELOG, CMakeLists.txt, Ponca/src/Fitting/algebraicSphere.h, Ponca/src/Fitting/basket.h, cmake/PoncaConfigureFitting.cmake, doc/src/ponca_module_fitting.mdoc, tests/common/testUtils.h, tests/src/algebraicsphere_primitive.cpp, tests/src/basket.cpp, tests/src/curvature_plane.cpp, tests/src/curvature_sphere.cpp, tests/src/deta_orthogonal_derivatives.cpp, tests/src/dnormal_plane.cpp, tests/src/dnormal_sphere.cpp, tests/src/dpotential_plane.cpp, tests/src/dpotential_sphere.cpp, tests/src/fit_line.cpp, tests/src/fit_monge_patch.cpp, tests/src/fit_plane.cpp, tests/src/fit_radius_curvature_center.cpp, tests/src/fit_unoriented.cpp, tests/src/gls_compare.cpp, tests/src/gls_paraboloid_der.cpp, tests/src/gls_sphere_der.cpp, tests/src/gls_tau.cpp, tests/src/normal_plane.cpp, tests/src/normal_sphere.cpp, tests/src/projection.cpp, tests/src/scale_space_consistency.cpp
Simplify use of KdTree queries in Basket objects
=> Add basket compute with ids

cmake/PoncaConfigureCommon.cmake, cmake/PoncaConfigureSpatialPartitioning.cmake
Replace 
```cmake
target_link_libraries(SpatialPartitioning PUBLIC INTERFACE Eigen3::Eigen)
``` 
by 
```cmake
if(Eigen3_FOUND)
target_link_libraries(SpatialPartitioning PUBLIC INTERFACE Eigen3::Eigen)
endif()
```
in `ConfigureSpatialPartitioning.cmake`.
=> Fix eigen transitive in Ponca::SpatialPartitioning

Ponca/src/Fitting/gls.hpp
This PR brings two fixes to build errors related to the GLSDer::geomVar() function:
1. The Base::isScaleDer() function was improperly called and seemed to yield a const correctedness error. For now its call was just replaced by a more direct test.
2.  Wrong namespace for some function calls
=> [Fitting] Fix errors in GLSDer::geomVar()

CHANGELOG, Ponca/src/Fitting/basket.h, Ponca/src/Fitting/covarianceFit.hpp, Ponca/src/Fitting/curvatureEstimation.hpp, Ponca/src/Fitting/defines.h, Ponca/src/Fitting/mean.h, Ponca/src/Fitting/meanPlaneFit.h, Ponca/src/Fitting/mlsSphereFitDer.hpp, Ponca/src/Fitting/orientedSphereFit.hpp, Ponca/src/Fitting/primitive.h, Ponca/src/Fitting/sphereFit.hpp, Ponca/src/Fitting/unorientedSphereFit.hpp, doc/src/ponca_module_fitting.mdoc, examples/cpp/nanoflann/ponca_nanoflann.cpp, tests/src/gls_paraboloid_der.cpp
This little modification fix this bug : 
- When using several pass, the basket multiplies the number of neighbors with the number of pass. 
Be careful, when you're using addNeighbor by hand, don't forget to update the m_nbNeighbors by hand too when using other pass.
=> Update nbNeighbors when using multiple pass

CHANGELOG, Ponca/src/Fitting/mean.h, Ponca/src/Fitting/orientedSphereFit.h, Ponca/src/SpatialPartitioning/KdTree/kdTree.h, Ponca/src/SpatialPartitioning/KdTree/kdTreeTraits.h, doc/src/example.mdoc, doc/src/example_cxx_neighbor_search.mdoc, doc/src/ponca_module_spatialpartitioning.mdoc, examples/cpp/CMakeLists.txt, examples/cpp/ponca_neighbor_search.cpp, tests/src/algebraicsphere_primitive.cpp, tests/src/dnormal_sphere.cpp
This PR 
- add a small `Ponca::KdTree` example to illustrate the use of neighbor searches 
- improve the documentation of the kd-tree (warning about index iterators + implementation details) 
- add a missing include (for using `Eigen::AxisAligned`)
- fix a few comments
=> Kd-tree documentation and small fixes

CHANGELOG, Ponca/src/Fitting/curvature.h, Ponca/src/Fitting/curvature.hpp, Ponca/src/Fitting/curvatureEstimation.hpp, doc/src/ponca_module_fitting.mdoc, examples/cpp/ponca_basic_cpu.cpp, tests/src/curvature_plane.cpp, tests/src/curvature_sphere.cpp, tests/src/fit_radius_curvature_center.cpp, tests/src/gls_paraboloid_der.cpp
This PR changes the convention used to store principal curvatures in the `CurvatureEstimatorBase` class.
Before, `k1` and `k2` where stored such that `|k1| > |k2|`, which was the sources of issues such as discontinuities appearing in visualization.
Now, principal curvatures are renamed in `kmin` and `kmax` and verify `kmin < kmax`.
**Questions** 
Is it the responsability of the caller of `CurvatureEstimatorBase::setCurvatureValues` to ensure that `kmin <= kmax` ? 
Or should the class always check and swap the curvature values and direction if necessary ? 
Right now the first solution is implemented since `Eigen` often compute eigenvalues in this "natural" order, but that can be changed. 
Note that encapsulation is already private. There is still one unused class that try to access them …
=> Change curvature convention to kmin <= kmax

CHANGELOG, Ponca/src/Fitting/mlsSphereFitDer.hpp, Ponca/src/Fitting/weightFunc.h
Here is a quick fix to the issue  #95.
The basis center is added to the local point to get back the point in global coordinates, and then call weight derivatives functions. 
Small disadvantage: the basis center is added here, but then subtracted in the weight function, so it is not the most efficient solution (except if the compiler is good enough to avoid these successive additions and substractions).
=> Fix MlsSphereFitDer weight derivatives (issue #95)

CHANGELOG, Ponca/src/Fitting/basket.h, tests/src/basket.cpp
This PR changes the hard-coded extension list for the `Basket` and `BasketDiff` types to a variadic list.
=> Use variadic template for basket extensions

CHANGELOG, Ponca/src/Fitting/covarianceFit.hpp, Ponca/src/Fitting/covarianceLineFit.h, Ponca/src/Fitting/enums.h, Ponca/src/Fitting/orientedSphereFit.hpp, Ponca/src/Fitting/primitive.h, Ponca/src/Fitting/sphereFit.hpp, Ponca/src/Fitting/unorientedSphereFit.hpp
This PR mainly fixes issue #100
It also improves
- the doc on `FIT_RESULT`
- the primitive base finalize
- the check on conflict
I have just a few questions or remarks
- the number of neighbors used to determine if a fit is stable or not should depends on the dimension right? For example, a PCA in 2D is stable with 2 neighbors, in 3D with 3 neighbors, etc... I wanted to be sure if it is correct for every fitting procedure and if it is pertinent to add this
- note that fitting an oriented sphere to 1 point and 1 normal vector in any dimension is always stable as it simply returns the plane that passes by this point with a normal equal to the normal of the input point. For 2 points in 2D I believe it is also quite stable in general. That being said, I am not sure for 2 points in 3D, the …
=> Fix current status (issue #100)

CHANGELOG, Ponca/src/SpatialPartitioning/KnnGraph/Query/knnGraphRangeQuery.h
Change internal implementation of the visited flag table: all points visited by the knn graphs are stored in a set, instead a fixed-size flag table.
This avoids to allocate tables of the size of the point cloud for each query.
=> KnnGraph: replace flag table by set

CHANGELOG, Ponca/src/SpatialPartitioning/KnnGraph/Query/knnGraphRangeQuery.h, Ponca/src/SpatialPartitioning/KnnGraph/knnGraph.h
Dear Nicolas,
This PR fixes building issues on my Linux:
- Some template parameters missing
- Calls to std::is_same_v (replaced with std::is_same::value)
Best,
Jules
=> Fix building errors

CHANGELOG, Ponca/src/Fitting/sphereFit.h, Ponca/src/Fitting/sphereFit.hpp, examples/cpp/ponca_basic_cpu.cpp
This PR fixes issue #112:
- use `EigenSolver` on `C^{-1}A`
- put the solver as class member in case we want to access it
- add example and documentation
=> Fix sphere fitting eigen solver

CHANGELOG, Ponca/src/Fitting/defines.h
In some use cases, having recursive access to the `Base` typedef of fitting types throughout a basket (i.e. going up the hierarchy tree of the CRTP) can be useful. This PR makes this typedef protected instead of private to allow for such recursive access.
=> [Fitting] Make base typedef of fitting types protected

CHANGELOG, Ponca/src/Common/Macro.h, Ponca/src/SpatialPartitioning/KdTree/Query/kdTreeQuery.h, Ponca/src/SpatialPartitioning/KdTree/kdTree.h, Ponca/src/SpatialPartitioning/KdTree/kdTree.hpp, Ponca/src/SpatialPartitioning/KdTree/kdTreeTraits.h
This PR changes the interface of the kd-tree node to make it more flexible.
Previously, the kd-tree implementation would access node fields directly, which does not allow nodes to customize what data they store and how that data is stored. Now everything is done through methods: the kd-tree calls methods to configure the nodes and the nodes provide accessors to the data the kd-tree and its queries need.
This PR also fixes some small bugs that were introduced with the kd-tree traits.
=> [SpatialPartitioning] Change the interface of kd-tree nodes

CHANGELOG, Ponca/src/SpatialPartitioning/KdTree/kdTree.h, Ponca/src/SpatialPartitioning/KdTree/kdTree.hpp
This PR removes some unused functions from the kd-tree API, as well as functions that should not be exposed (e.g. non const accessors to internal data).
This PR also fixes the `valid` function of the kd-tree that used to crash immediately upon entry in debug.
=> [SpatialPartitioning] Clean up kdtree API

CHANGELOG, Ponca/src/SpatialPartitioning/KdTree/kdTree.h, Ponca/src/SpatialPartitioning/KdTree/kdTree.hpp
This PR changes the output of the `to_string` function of the KdTree:
- The output data now uses the YAML format
- A `verbose` (optional) argument was added to `to_string`, which will prevent the samples and the node data to be output into the string if false
- Additional info about the KdTree was also added to the start of the output string
The resulting YAML should be correct (tested with an [online parser](https://codebeautify.org/yaml-parser-online/y230817b0)).
=> [SpatialPartitioning] Improve kdtree to_string

CHANGELOG, Ponca/src/SpatialPartitioning/KdTree/kdTreeTraits.h, doc/src/ponca_module_spatialpartitioning.mdoc, examples/cpp/CMakeLists.txt, examples/cpp/ponca_customize_kdtree.cpp
Add type `KdTreeCustomizableNode` to simplify `KdNode` customization without needed to redefine traits.
Documentation and examples have been added to describe usage.
This PR does not change the client API, so could be included in v.1.2.
=> Simplify KdTree Node type specialization

CHANGELOG, Ponca/src/Fitting/algebraicSphere.h, tests/src/gls_paraboloid_der.cpp
Fix #118 
- remove normalization of the gradient of the algebraic sphere in `primitveGradient()`
- the test `gls_paraboloid_der` estimates the derivative of the normal using finite difference on the gradient, so a call to `normalized()` on the gradient is added in this test
=> Fix sphere gradient (#118)

CHANGELOG, Ponca/src/SpatialPartitioning/KdTree/Query/kdTreeKNearestQueries.h, Ponca/src/SpatialPartitioning/KdTree/Query/kdTreeNearestQueries.h, Ponca/src/SpatialPartitioning/KdTree/Query/kdTreeQuery.h, Ponca/src/SpatialPartitioning/KdTree/Query/kdTreeRangeQueries.h, Ponca/src/SpatialPartitioning/KdTree/kdTree.h, Ponca/src/SpatialPartitioning/KdTree/kdTree.hpp, Ponca/src/SpatialPartitioning/KnnGraph/knnGraph.h, examples/cpp/ponca_basic_cpu.cpp, examples/cpp/ponca_customize_kdtree.cpp, tests/src/basket.cpp
This PR renames some of the KdTree accessors and changes its `to_string` method to a `print` method taking an `std::ostream` as argument. This PR also adds an `operator<<` overload for the KdTree.
Most notably, the `index_data` method was renamed to `samples` to work on solving the confusion raised by how the KdTree handles sampling (see #114).
=> [SpatialPartitioning] Change part of the kdtree API

CHANGELOG, Ponca/src/Fitting/algebraicSphere.h, Ponca/src/Fitting/algebraicSphere.hpp, Ponca/src/Fitting/covarianceFit.hpp, Ponca/src/Fitting/covarianceLineFit.h, Ponca/src/Fitting/covariancePlaneFit.hpp, Ponca/src/Fitting/linePrimitive.h, Ponca/src/Fitting/mean.h, Ponca/src/Fitting/meanPlaneFit.h, Ponca/src/Fitting/plane.h, Ponca/src/Fitting/weightFunc.h, Ponca/src/Fitting/weightFunc.hpp, tests/src/fit_cov.cpp
In the current version it is not clear that the barycenter is given in local coordinate system.
=> [Fitting] Expose barycenter and add barycenterLocal

CHANGELOG, CMakeLists.txt, cmake/Config.cmake.in, cmake/PoncaConfigureCommon.cmake, cmake/PoncaConfigureFitting.cmake, cmake/PoncaConfigureSpatialPartitioning.cmake
=> Enable targets exportation during build

CHANGELOG, Ponca/src/SpatialPartitioning/KdTree/kdTreeTraits.h
On MSVC, the `MAX_NODE_COUNT` enum value does not automatically get promoted to `std::size_t` when it is too big which generates an error ([C4309](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-2-c4309?view=msvc-170)). This PR simply forces the enum to have `std::size_t` as the underlying type.
=> [SpatialPartitioning] Force max node count type to 'std::size_t'

CHANGELOG, Ponca/src/SpatialPartitioning/query.h
Compilation error observed with appleclang
=> [SpatialPartioning] Fix compilation error: wrong initializers ordering

CHANGELOG, doc/src/ponca_module_fitting.mdoc
=> Adding the missing base from the curvature estimator in the Fitting user manual

CHANGELOG, Ponca/src/Fitting/basket.h, Ponca/src/Fitting/compute.h, Ponca/src/Fitting/primitive.h, cmake/PoncaConfigureFitting.cmake
Removes the uses of `WRITE_COMPUTE_FUNCTIONS` macro in `src/Fitting/basket.h` by defining the compute functions directly in the Basket` class.
=> [fitting] Streamlining compute functions declaration

.github/workflows/ContinuousTest.yml, CHANGELOG
The goal is to reduce ci times when tests fails.
In this version, the project is configured without the examples first, then the tests are compiled.
If it goes fine, PCL is fetched, the project is re-configured with examples enables.
=> [ci] Do not configure examples (and fetch deps.) for testing
